version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_app
    restart: always
    ports:
      - "9000:9000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: testdb
      DB_USERNAME: testuser
      DB_PASSWORD: testpass
    volumes:
      - ./php/src:/var/www/html

volumes:
  mysql_data:
